"""Post-merge orchestration: glue between the pure modules and GitHub I/O.

Imported lazily by app.py on `pull_request/closed` webhook events when
`pr["merged"]` is True. Spawned on a background thread (same pattern as
`_queue_review`) so the webhook handler returns 200 fast and never blocks
GitHub's delivery loop on slow LLM / git operations.

Defensive: every disk + GitHub I/O failure is caught and logged. The
function never raises; on error it returns `{"error": <str>}` so the
caller can log a single line and move on.
"""

from __future__ import annotations

import os
import sys
import traceback
from datetime import datetime, timezone
from typing import Dict, List, Optional

# Local sibling modules (these are pure).
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import app  # noqa: E402 — late binding so tests can patch helpers wholesale
import review_store  # noqa: E402
from post_merge import changelog as changelog_mod  # noqa: E402
from post_merge import followups as followups_mod  # noqa: E402
from post_merge import release as release_mod  # noqa: E402

# Re-export so tests + callers don't have to dig into app.py for it.
PushProtectedError = app.PushProtectedError

# Process-local cache of which `owner/repo` combinations had `put_file` to
# main return 403. Once seen, we skip the direct-commit attempt and go
# straight to auto-PR mode for subsequent commits in the same process.
_PROTECTED_REPOS: Dict[str, bool] = {}


def _now_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _read_local_changelog(repo_path: str, changelog_path: str) -> str:
    """Read CHANGELOG.md from the locally-synced clone. Empty string if missing."""
    full = os.path.join(repo_path, changelog_path)
    if not os.path.isfile(full):
        return ""
    try:
        with open(full, "r") as fh:
            return fh.read()
    except OSError:
        return ""


def _commit_changelog_direct(
    owner: str,
    repo: str,
    path: str,
    new_content: str,
    branch: str,
    message: str,
    token: str,
) -> bool:
    """Attempt a direct push to `branch`. Returns True on success.

    Raises PushProtectedError on 403 so the caller can switch to auto-PR
    mode. Other failures bubble up as exceptions to be caught by the
    outer orchestrator.
    """
    sha = app.get_file_sha(owner, repo, path, branch, token)
    app.put_file(
        owner=owner,
        repo=repo,
        path=path,
        content=new_content,
        message=message,
        branch=branch,
        sha=sha,
        token=token,
    )
    return True


def _commit_changelog_via_pr(
    owner: str,
    repo: str,
    path: str,
    new_content: str,
    base_branch: str,
    pr_number: int,
    message: str,
    token: str,
) -> Optional[int]:
    """Open (or reuse) an auto-PR with the changelog amendment.

    Returns the PR number, or None on failure.
    """
    branch_name = f"seneschal/changelog-{pr_number}"
    try:
        base_sha = app.get_default_branch_sha(owner, repo, base_branch, token)
        app.create_branch(owner, repo, branch_name, base_sha, token)
        sha = app.get_file_sha(owner, repo, path, branch_name, token)
        app.put_file(
            owner=owner,
            repo=repo,
            path=path,
            content=new_content,
            message=message,
            branch=branch_name,
            sha=sha,
            token=token,
        )
        pr = app.create_pull_request(
            owner=owner,
            repo=repo,
            title=f"chore(changelog): record #{pr_number}",
            body=f"Auto-generated by Seneschal — main is protected so the changelog update lands via PR.\n\nClosing #{pr_number} prompted this entry.",
            head=branch_name,
            base=base_branch,
            token=token,
            draft=False,
        )
        # Apply the seneschal:changelog label so the operator can filter.
        try:
            app.apply_labels(owner, repo, pr.get("number"), ["seneschal:changelog"], token)
        except Exception:
            pass
        return int(pr.get("number") or 0) or None
    except Exception as e:  # noqa: BLE001
        app.log(f"[post_merge] changelog auto-PR failed for {owner}/{repo}#{pr_number}: {e!r}")
        return None


def _changelog_step(
    owner: str,
    repo: str,
    pr_number: int,
    pr_meta: dict,
    config,
    token: str,
    repo_path: str,
) -> bool:
    """Read CHANGELOG.md, insert the entry, push it. Returns True on success."""
    title = pr_meta.get("title") or ""
    pr_url = pr_meta.get("html_url") or f"https://github.com/{owner}/{repo}/pull/{pr_number}"
    kind = changelog_mod.classify_prefix(title) or "chore"
    entry = changelog_mod.format_unreleased_entry(pr_number, title, pr_url)
    existing = _read_local_changelog(repo_path, config.post_merge.changelog_path)
    new_content = changelog_mod.insert_unreleased_entry(existing, entry, kind)
    if new_content == existing:
        # Nothing changed — skip the push.
        return False

    repo_slug = f"{owner}/{repo}"
    base_branch = config.post_merge.release_base_branch or "main"
    stripped = changelog_mod._strip_prefix(title)
    commit_message = f"chore(changelog): add #{pr_number} {stripped}"

    # If we already know main is protected, skip the direct attempt.
    if _PROTECTED_REPOS.get(repo_slug):
        pr_no = _commit_changelog_via_pr(
            owner, repo, config.post_merge.changelog_path, new_content,
            base_branch, pr_number, commit_message, token,
        )
        return pr_no is not None

    try:
        _commit_changelog_direct(
            owner, repo, config.post_merge.changelog_path, new_content,
            base_branch, commit_message, token,
        )
        return True
    except PushProtectedError:
        app.log(f"[post_merge] {repo_slug} main protected — switching to auto-PR mode")
        _PROTECTED_REPOS[repo_slug] = True
        pr_no = _commit_changelog_via_pr(
            owner, repo, config.post_merge.changelog_path, new_content,
            base_branch, pr_number, commit_message, token,
        )
        return pr_no is not None


def _followups_step(
    owner: str,
    repo: str,
    pr_number: int,
    pr_meta: dict,
    config,
    token: str,
) -> List[int]:
    """Parse [FOLLOWUP] markers from the stored review and file issues for new ones."""
    repo_slug = f"{owner}/{repo}"
    review = review_store.get_review(repo_slug, pr_number)
    if review is None:
        return []
    parsed = followups_mod.parse_followups(review.body)
    if not parsed:
        return []
    # Idempotence: skip followups whose normalized titles match issues we've
    # already filed (best-effort — we don't have title-of-issue stored, so
    # the cheap heuristic is "if followups_filed already has N entries and
    # there are <=N parsed, do nothing"). The accurate dedupe lives in P2's
    # SQLite index; this is the cheap-but-good-enough version.
    already = list(review.followups_filed or [])
    if len(parsed) <= len(already):
        return []
    # File the surplus.
    needed = parsed[len(already):]
    label = config.post_merge.followup_label or "seneschal-followup"
    pr_url = pr_meta.get("html_url") or f"https://github.com/{owner}/{repo}/pull/{pr_number}"
    new_numbers: List[int] = []
    for f in needed:
        try:
            body = f"{f.body_excerpt}\n\n---\nFiled by Seneschal from #{pr_number}: {pr_url}"
            issue = app.create_issue(
                owner=owner,
                repo=repo,
                title=f.title,
                body=body,
                labels=[label],
                token=token,
            )
            num = int(issue.get("number") or 0)
            if num:
                new_numbers.append(num)
        except Exception as e:  # noqa: BLE001
            app.log(f"[post_merge] create_issue failed on {repo_slug}#{pr_number}: {e!r}")
            break
    return new_numbers


def _release_step(
    owner: str,
    repo: str,
    pr_meta: dict,
    config,
    token: str,
    repo_path: str,
) -> Optional[int]:
    """Open or amend a release PR if accumulated bump >= configured threshold."""
    threshold = (config.post_merge.release_threshold or "").lower()
    if threshold not in {"patch", "minor", "major"}:
        return None
    existing = _read_local_changelog(repo_path, config.post_merge.changelog_path)
    if not existing:
        return None
    # Extract the Unreleased block.
    import re as _re
    m = _re.search(r"^## \[Unreleased\][^\n]*\n(.*?)(?=^## |\Z)", existing, _re.MULTILINE | _re.DOTALL)
    if not m:
        return None
    unreleased_lines = m.group(1).split("\n")
    bump = release_mod.bump_kind(unreleased_lines)
    order = {"patch": 0, "minor": 1, "major": 2}
    if order.get(bump, 0) < order.get(threshold, 0):
        return None

    # If a release PR is already open, amend it instead of opening another.
    try:
        existing_prs = app.find_open_prs_with_label(owner, repo, "seneschal:release", token)
    except Exception:  # noqa: BLE001
        existing_prs = []
    if existing_prs:
        # Race: amend the changelog on the existing branch and bail.
        head_ref = (existing_prs[0].get("head") or {}).get("ref")
        if head_ref:
            try:
                sha = app.get_file_sha(owner, repo, config.post_merge.changelog_path, head_ref, token)
                app.put_file(
                    owner=owner,
                    repo=repo,
                    path=config.post_merge.changelog_path,
                    content=existing,
                    message=f"chore(release): refresh CHANGELOG (Seneschal)",
                    branch=head_ref,
                    sha=sha,
                    token=token,
                )
            except Exception as e:  # noqa: BLE001
                app.log(f"[post_merge] amend release-PR failed: {e!r}")
        return int(existing_prs[0].get("number") or 0) or None

    # Open a fresh release PR.
    # We don't currently extract the prior version — leave the version
    # bump computation as informational; the operator decides the final
    # tag at merge time.
    new_version = "next"  # placeholder; the PR body explains the bump kind
    branch = f"seneschal/release-{new_version}"
    base = config.post_merge.release_base_branch or "main"
    try:
        base_sha = app.get_default_branch_sha(owner, repo, base, token)
        app.create_branch(owner, repo, branch, base_sha, token)
        # Touch the changelog on the new branch so the PR has a diff.
        sha = app.get_file_sha(owner, repo, config.post_merge.changelog_path, branch, token)
        app.put_file(
            owner=owner,
            repo=repo,
            path=config.post_merge.changelog_path,
            content=existing,
            message=f"chore(release): prep release ({bump} bump)",
            branch=branch,
            sha=sha,
            token=token,
        )
        pr = app.create_pull_request(
            owner=owner,
            repo=repo,
            title=f"chore(release): {bump} release prep",
            body=f"Accumulated `## [Unreleased]` entries warrant a `{bump}` bump.\n\nFinalize the version + cut the tag when ready.",
            head=branch,
            base=base,
            token=token,
            draft=bool(config.post_merge.release_pr_draft),
        )
        try:
            app.apply_labels(owner, repo, pr.get("number"), ["seneschal:release"], token)
        except Exception:
            pass
        return int(pr.get("number") or 0) or None
    except Exception as e:  # noqa: BLE001
        app.log(f"[post_merge] open release-PR failed for {owner}/{repo}: {e!r}")
        return None


def handle_pr_merged(
    owner: str,
    repo: str,
    pr_number: int,
    installation_id: int,
    pr_meta: dict,
    config,
) -> dict:
    """Top-level entrypoint. Sequences changelog → followups → release.

    Returns a status dict for caller logging; never raises.
    """
    result = {
        "changelog_updated": False,
        "followups_filed": [],
        "release_pr": None,
    }
    try:
        token = app.get_installation_token(installation_id)

        # Sync the local clone so changelog reads + analyzer-style ops can
        # see the post-merge tree.
        head_ref = (pr_meta.get("base") or {}).get("ref") or config.post_merge.release_base_branch or "main"
        head_sha = pr_meta.get("merge_commit_sha") or (pr_meta.get("head") or {}).get("sha", "")
        try:
            repo_path = app.ensure_repo_synced(owner, repo, head_ref, head_sha, token)
        except Exception as e:  # noqa: BLE001
            app.log(f"[post_merge] repo sync failed for {owner}/{repo}#{pr_number}: {e!r}")
            repo_path = ""

        # 1. Changelog.
        if config.post_merge.changelog and repo_path:
            try:
                result["changelog_updated"] = _changelog_step(
                    owner, repo, pr_number, pr_meta, config, token, repo_path,
                )
            except Exception as e:  # noqa: BLE001
                app.log(f"[post_merge] changelog step failed for {owner}/{repo}#{pr_number}: {e!r}")

        # 2. Followups.
        new_followups: List[int] = []
        if config.post_merge.followups:
            try:
                new_followups = _followups_step(
                    owner, repo, pr_number, pr_meta, config, token,
                )
            except Exception as e:  # noqa: BLE001
                app.log(f"[post_merge] followups step failed for {owner}/{repo}#{pr_number}: {e!r}")
        result["followups_filed"] = new_followups

        # 3. Mark merged in the review store (records merged_at + dedup the
        # followup numbers). Always do this when there's a stored review,
        # even if no followups fired this round — gives P2's index a stable
        # `merged_at` field.
        merged_at = pr_meta.get("merged_at") or _now_iso()
        try:
            review_store.mark_merged(f"{owner}/{repo}", pr_number, merged_at, new_followups)
        except Exception as e:  # noqa: BLE001
            app.log(f"[post_merge] mark_merged failed for {owner}/{repo}#{pr_number}: {e!r}")

        # 4. Release PR (depends on the changelog already being updated).
        if config.post_merge.release_threshold and repo_path:
            try:
                result["release_pr"] = _release_step(
                    owner, repo, pr_meta, config, token, repo_path,
                )
            except Exception as e:  # noqa: BLE001
                app.log(f"[post_merge] release step failed for {owner}/{repo}#{pr_number}: {e!r}")

        return result
    except Exception as e:  # noqa: BLE001
        app.log(f"[post_merge] orchestrator failed for {owner}/{repo}#{pr_number}: {e!r}\n{traceback.format_exc()}")
        result["error"] = f"{type(e).__name__}: {e}"
        return result
